### ISSUE TITLE
PROXY_PORT not defined

### ISSUE THREAD

**Issue by rscorer** [smarterclayton/openshift-redis-cart#12]
In the manifest, I can see

```
Public-Port-Name:  PROXY_PORT
```

Yet there is no $OPENSHIFT_REDIS_PROXY_PORT so I am unable to access the redis from an external device?

I'm installing exactly as you state in the README, is there something else I need to do?

**Comment by abemedia** [comment]
I'm having the same issue. Am trying to access a redis cartridge from multiple gears. Did you manage in the end?

**Comment by svsa** [comment]
my needs changed, but i *think* i worked around this in a very quick test by creating a scalable PHP gear and adding the REDIS cartridge to that gear. I didn't actually need the PHP gear, it was just a transport mechanism to get REDIS available to my other gear... and I didn't make any notes as to whether it worked or not. Sorry! HTH

**Comment by rscorer** [comment]
my needs changed, but i think i worked around this in a very quick test by creating a scalable PHP gear and adding the REDIS cartridge to that gear. I didn't actually need the PHP gear, it was just a transport mechanism to get REDIS available to my other gear... and I didn't make any notes as to whether it worked or not. Sorry! HTH
